run:
  issues-exit-code: 1
  tests: false

linters:
  enable:
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 25
  cyclop:
    max-complexity: 25
  gocognit:
    min-complexity: 50
  nestif:
    min-complexity: 10
  gosec:
    severity: medium
    confidence: medium
  lll:
    line-length: 120
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude:
    - "exported .* should have comment or be unexported"
    - "package comment should be of the form"
    - "G104:"
